# Notes:
# the auto_show  property decides which panels open automatically.
# As a side effect, the gui renderering code for panels with auto_show=true will be precompiled while
# others will not.

[general]
    data_path = "/mnt/datadrive/DATA"

[[component]]
    type="ImageViewer"
    name = "Image Viewer"
 
[[component]]
    type="ImageViewer"
    name = "Image Viewer 2"
    auto_show = true

    
[[component]]
    type="ImageViewer"
    name = "Image Viewer 3"

# [[component]]
#     type = "ImageFeed"
#     name = "GoldEye (uncalibrated)"
#     input-channel = "aeron:ipc"
#     input-stream = 1003
#     auto_show = true

[[component]]
    type = "ImageFeed"
    name = "GoldEye"
    input-channel = "aeron:ipc"
    input-stream = 1013
    auto_show = true


# [[component]]
#     type="ImageFeed"
#     name="CRED2 (uncalibrated)"
#     input-channel="aeron:ipc"
#     input-stream=1001
#     auto_show = true

#     # crop = true
#     # cropx = [147,467]
#     # cropy = [67,387]


# [[component]]
#     type="ImageFeed"
#     name="IFTS (uncalibrated)"
#     input-channel="aeron:ipc"
#     input-stream=1006
#     auto_show = true
    
[[component]]
    type="ImageFeed"
    name="IFTS"
    input-channel="aeron:ipc"
    input-stream=1016
    auto_show = true
    

[[component]]
    type="ImageFeed"
    name="CRED2"
    input-channel="aeron:ipc"
    input-stream=1011
    auto_show = true

    # crop = true
    # cropx = [147,467]
    # cropy = [67,387]

[[component]]
    type="ImageFeed"
    name="CRED2: Differential"
    input-channel="aeron:ipc"
    input-stream=5003
    auto_show = true

    # crop = true
    # cropx = [147,467]
    # cropy = [67,387]


[[component]]
    type="ImageFeed"
    name="CRED2: Un-Fringed"
    input-channel="aeron:ipc"
    input-stream=5001
    auto_show = true

    # crop = true
    # cropx = [147,467]
    # cropy = [67,387]



[[component]]
    type="ImageFeed"
    name="CRED2: Fringed"
    input-channel="aeron:ipc"
    input-stream=5002
    auto_show = true

    # crop = true
    # cropx = [147,467]
    # cropy = [67,387]

[[component]]
    type="DMFeed"
    name="LOWFS Residual"
    valid-actuator-map="/mnt/datadrive/DATA/dm/BAX307-valid-actu-map.fits"
    actuator-map="/mnt/datadrive/DATA/dm/BAX307-actu-map.fits"
    input-channel="aeron:ipc"
    input-stream=2001
    auto_show = true
    idle-timeout = 0.01


[[component]]
    type="DMFeed"
    name="LOWFS Prediction"
    valid-actuator-map="/mnt/datadrive/DATA/dm/BAX307-valid-actu-map.fits"
    actuator-map="/mnt/datadrive/DATA/dm/BAX307-actu-map.fits"
    input-channel="aeron:ipc"
    input-stream=9001
    auto_show = true
    idle-timeout = 0.01



[[component]]
    type="DMFeed"
    name="DM Mixer Output"
    valid-actuator-map="/mnt/datadrive/DATA/dm/BAX307-valid-actu-map.fits"
    actuator-map="/mnt/datadrive/DATA/dm/BAX307-actu-map.fits"
    input-channel="aeron:ipc"
    input-stream=105
    auto_show = true
    idle-timeout = 1.0

[[component]]
    type="DMFeed"
    name="Calibration Offset"
    valid-actuator-map="/mnt/datadrive/DATA/dm/BAX307-valid-actu-map.fits"
    actuator-map="/mnt/datadrive/DATA/dm/BAX307-actu-map.fits"
    input-channel="aeron:ipc"
    input-stream=104
    auto_show = true
    idle-timeout = 1e30 # never timeout

[[component]]
    type="DMFeed"
    name="User Offset"
    valid-actuator-map="/mnt/datadrive/DATA/dm/BAX307-valid-actu-map.fits"
    actuator-map="/mnt/datadrive/DATA/dm/BAX307-actu-map.fits"
    # input-channel="aeron:ipc"
    # input-stream=1007
    input-channel="aeron:ipc"
    input-stream=103
    auto_show = true
    idle-timeout = 1e30 # never timeout

[[component]]
    type="DMFeed"
    name="SCC Residual"
    valid-actuator-map="/mnt/datadrive/DATA/dm/BAX307-valid-actu-map.fits"
    actuator-map="/mnt/datadrive/DATA/dm/BAX307-actu-map.fits"
    input-channel="aeron:ipc"
    input-stream=6000
    auto_show = true
    idle-timeout = 10.0

[[component]]
    type="DMFeed"
    name="Integrator Output"
    valid-actuator-map="/mnt/datadrive/DATA/dm/BAX307-valid-actu-map.fits"
    actuator-map="/mnt/datadrive/DATA/dm/BAX307-actu-map.fits"
    input-channel="aeron:ipc"
    input-stream=7000
    auto_show = true
    idle-timeout = 10.0


[[component]]
    type="DMOffsetTool"
    name="DM Offset Tool"
    zern-modes="/mnt/datadrive/DATA/dm/zern-to-actus.fits"
    lowfs-modes="/mnt/datadrive/DATA/LOWFS/modes-to-actus.fits"
    fourier-modes="/mnt/datadrive/DATA/SCC/modemat-all.fits"
    actuator-map="/mnt/datadrive/DATA/dm/BAX307-actu-map.fits"
    valid-actuator-map="/mnt/datadrive/DATA/dm/BAX307-valid-actu-map.fits"
    output-channel="aeron:ipc"
    output-stream=103
    output-key="offset"
    auto_show = true

[[component]]
    type="DMOffsetTool"
    name="DM CalibOffset Tool"
    zern-modes="/mnt/datadrive/DATA/dm/zern-to-actus.fits"
    lowfs-modes="/mnt/datadrive/DATA/LOWFS/modes-to-actus.fits"
    fourier-modes="/mnt/datadrive/DATA/SCC/modemat-all.fits"
    actuator-map="/mnt/datadrive/DATA/dm/BAX307-actu-map.fits"
    valid-actuator-map="/mnt/datadrive/DATA/dm/BAX307-valid-actu-map.fits"
    output-channel="aeron:ipc"
    output-stream=104
    output-key="calibration"
    auto_show = true


[[component]]
    type="RTCBlock1"
    name="DM Mixer"
    auto_show=true
    event-channel="aeron:ipc"
    event-stream=101
    status-channel="aeron:ipc"
    status-stream=102
    
    event-buttons = [
        "Exit",
        "Reset",
        "Stop",
        "Play",
        "Pause",
        "StatusRequest",
    ]
    event-fields = [
        # name, type, default
        ["serialno", "String", "BAX307"],
        ["clip", "Float64", "0.5"],
        ["bestflat", "array", "/mnt/datadrive/DATA/dm/bestflat.fits"],
    ]


[[component]]
    type="RTCBlock1"
    name="Integrator"
    auto_show=true
    event-channel="aeron:ipc"
    event-stream=401
    status-channel="aeron:ipc"
    status-stream=402
    
    event-buttons = [
        "Exit",
        "Reset",
        "Stop",
        "Play",
        "Pause",
        "StatusRequest",
    ]
    event-fields = [
        # name, type, default
        ["gain", "Float64", "0.1"],
        ["leak", "Float64", "0.01"],
        ["clip", "Float64", "0.2"],
        ["modes_to_actus", "array", "/mnt/datadrive/DATA/SCC/modes-to-actus.fits"],
        ["actus_to_modes", "array", "/mnt/datadrive/DATA/SCC/actus-to-modes.fits"],
        ["invis_modes_to_actus", "array", "/mnt/datadrive/DATA/SCC/invis-modes-to-actus.fits"],
        ["actus_to_invis_modes", "array", "/mnt/datadrive/DATA/SCC/actus-to-invis-modes.fits"],

    ]

[[component]]
    type="RTCBlock1"
    name="LOWFS"
    auto_show=true
    event-channel="aeron:ipc"
    event-stream=301
    status-channel="aeron:ipc"
    status-stream=302
    
    event-buttons = [
        "Exit",
        "Reset",
        "Stop",
        "Play",
        "Pause",
        "StatusRequest",
    ]
    event-fields = [
        # name, type, default
        ["image_mask", "array",      "/mnt/datadrive/DATA/LOWFS/image-mask.fits"],
        ["cog_image_mask", "array",  "/mnt/datadrive/DATA/LOWFS/cog-image-mask.fits"],
        ["reference_image", "array", "/mnt/datadrive/DATA/LOWFS/reference-image.fits"],
        ["image_to_modes", "array",  "/mnt/datadrive/DATA/LOWFS/image-to-modes.fits"],
        ["modes_to_actus", "array",  "/mnt/datadrive/DATA/LOWFS/modes-to-actus.fits"],
        ["slopes_to_TT", "array",    "/mnt/datadrive/DATA/LOWFS/slopes-to-TT.fits"],
        ["cog_reference", "array-paddle",   "/mnt/datadrive/DATA/LOWFS/cog-reference.fits"],
    ]


# [[component]]
#     type="RTCBlock1"
#     name="Archiver"
#     auto_show=true
#     event-channel="aeron:ipc"
#     event-stream=201
#     status-channel="aeron:ipc"
#     status-stream=102
#         event-buttons = [
#         "Exit",
#         "Reset",
#         "Stop",
#         "Play",
#         "Pause",
#         "StatusRequest",
#     ]
#     event-fields = [
#         # name, type, default
#         ["uri", "String", "aeron:ipc"],
#         ["stream", "Float64", "1101"],
#         ["enabled", "Float64", "1.0"],
#     ]

[[component]]
    type="TTMonitor"
    name="TT Monitor"
    modes-to-actus="/mnt/datadrive/DATA/dm/zern-to-actus.fits"
    history-length=850
    input-channel="aeron:ipc"
    input-stream=7000
    auto_show = true

[[component]]
    type="TTMonitor"
    name="LOWFS TT Residual"
    modes-to-actus="/mnt/datadrive/DATA/dm/zern-to-actus.fits"
    history-length=850
    input-channel="aeron:ipc"
    input-stream=2001
    auto_show = true


# [[component]]
#     name = "Integrator Control"
#     type = "Integrator"
#     url-scc = "http://localhost:8009"
#     url-lowfs = "http://localhost:8008"
#     url-integ = "http://localhost:8010"
#     auto_show = true
